### ISSUE TITLE
chrome的问题 找不到其他提问的地方，麻烦看一下

### ISSUE THREAD

**Issue by gitlsl** [shuax/custom_crc32#1]
我现在装的是 最新版， 但他跳转的时候有个问题
比如我从 钉钉 或者 其他的软件打开  https://www.baidu.com  时， 会多出后面的启动参数变成

https://www.baidu.com%20--with-chrome-plus-plus%20--disable-features=RendererCodeIntegrity,FlashDeprecationWarning%20%22--user-data-dir=D:\Program%20Files\chrome\Data%22

也不是所有的软件都这样，  qq里跳转的话 就好的，不知道这个如何解决呢 谢谢

**Comment by gitlsl** [comment]
在你的新浪微博看到了   问题已修复    但是1.3.2在哪下载呢。。。

**Comment by shuax** [comment]
官网下载，网盘已经更新
